version: "3.7"
services: 
  database:
    image: mysql
    container_name: database
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports: 
      - ${DB_PORT}:${DB_PORT}
    networks: 
      - rede
  api:
    build: 
      context: "./api"
      dockerfile: Dockerfile
    container_name: api
    environment:
      - PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=${DB_SCHEMA}
    expose: 
      - ${API_PORT}
    volumes: 
      - "./api:/usr/src/api"
      - /usr/src/api/node_modules
    ports: 
      - ${API_PORT}:${API_PORT}
    depends_on: 
      - database
    networks: 
      - rede
  app:
    build: 
      context: "./app"
      dockerfile: Dockerfile
    container_name: app
    environment:
      - PORT=${APP_PORT}
    expose: 
      - ${APP_PORT}
    volumes:
      - "./app:/usr/src/app"
      - /usr/src/app/node_modules
    ports: 
      - ${APP_PORT}:${APP_PORT}
    depends_on: 
      - api
    networks: 
      - rede
networks: 
  rede: 
    driver: bridge